# My variables
name: 318BR
description: Who cares?
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]
tag_dir: tags

# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false

highlighter: rouge
